apiVersion: v1
kind: Service
metadata:
  name: fenice
  labels:
    app: fenice
spec:
  type: ClusterIP
  selector:
    app: fenice
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
